input_a = input('Nama: ')
A=input_a.split()
input_b = input('Tempat Tanggal Lahir: ')
B=input_b.split()
print("Haloo!", A[1], end=",")
print(A[0], end=" ")
print("\nAnda lahir di ", B[0], end=" pada tanggal ")
print(B[1], end=",")
print(B[2], end=" ")
print(B[3])
